# The config file

noise_model_t: 0.
noise_level_img: 0.
feature: 2048

seed: 42
image_list_file: data/ffhq_100_val.txt
image_dir: data/
name_folder_result: ffhq_pnp_20
output_csv: metrics.csv
model_path: model/ffhq_10m.pt

sigma                   : 0.001  # noise level associated with condition y
lambda_                 : 6.               # key parameter lambda            # use analytical solution
eta                     : 0.0               # eta for ddim samplingn  
zeta                    : 1.
guidance_scale          : 1.0   

num_train_timesteps     : 1000
iter_num                : 20            # set number of iterations


# noise schedule 
beta_start              : 0.0001
beta_end                : 0.02


# Guided diffusion
guided_diffusion:

  num_channels: 128
  num_res_blocks: 1
  attention_resolutions: "16"
  diffusion_steps: 1000
  noise_schedule: 'linear'
  num_head_channels: 64
  resblock_updown: True
  use_fp16: False
  use_scale_shift_norm: True
  num_heads: 4
  num_heads_upsample: -1
  use_new_attention_order: False
  timestep_respacing: ""
  use_kl: False
  predict_xstart: False
  rescale_timesteps: False
  rescale_learned_sigmas: False
  channel_mult: "1,1,2,2,4,4"
  learn_sigma: True
  class_cond: False
  use_checkpoint: False
  image_size: 256
  dropout: 0.
